### PR TITLE
Added Dropdown Menu

### PR DESCRIPTION
**Pull request by joshuadijamco**
1. User selects dropdown category (search criteria)
2. User uploads .db (map) file to the Dropzone
3. The dropdown is disabled and the user will have to refresh the page to try another search criteria

I was having issues getting the map to update dynamically -- so to make it user friendly, I just disabled the dropdown after the map was uploaded so that the user wasn't expecting any changes.

**Changes:**
- Refactored Dropzone.js slightly and made changes for Dropzone.js to accept searchCriteria
- Added Dropdown component to index.js 
- Added new NPM module "react-dropdown" (be sure to npm install)

### CODE REVIEW

**Comment by joshuadijamco** [comment]
Erroneously created pull request to parent repository, please disregard.

**Comment by panathea** [comment]
A recommended refactor that would allow you to fix your dynamic map would be to move the code for parsing the file into a custom hook like `const locations = useWorldLocations(worldFile, mapType)`—have the dropzone simply supply the file and then move all the searching code into the hook.

**Comment by panathea** [comment]
I'm also not opposed to adding more functionality to the parent repo if you'd like to collaborate ✌️

**Comment by joshuadijamco** [comment]
> A recommended refactor that would allow you to fix your dynamic map would be to move the code for parsing the file into a custom hook like `const locations = useWorldLocations(worldFile, mapType)`—have the dropzone simply supply the file and then move all the searching code into the hook.

That makes sense! When I was editing it, I noticed that the "event" would only trigger in the Dropzone, but I didn't want to edit it as much. I think that your solution would work! The user will be able to update the dropdown (with the various search terms) and in effect, the map will dynamically update as well. (no more need for the refresh and disabling the dropdown for user experience)

**Pull request closed without merging**
